# SITE SETTINGS
title: Craywatch
author: INBO
url: "https://craywatch.inbo.be" # Custom domain is not set via CNAME, so url and baseurl need to be indicated
baseurl: "" # Otherwise GitHub Pages will set this to "/craywatch"


# SOCIAL PROFILES
social:
  github: inbo/craywatch

# THEME SETTINGS (ALL OPTIONAL)
posts_on_home: 3
# tweets_on_home: true
archive_permalink: /blog/
remote_theme: peterdesmet/petridish@3.0
github_edit: true
colors:
  links: "#007bff"
  banner: "#007bff"
  footer: "#6c757d"
font_serif: true
rounded_corners: true
logo: /assets/images/logo.png

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - map/map.html

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: posts
    values:
      permalink: "/blog/:year/:slug/"
