# SITE SETTINGS
title: Craywatch
author: INBO
url: "https://craywatch.inbo.be" # Custom domain is not set via CNAME, so url and baseurl need to be indicated
baseurl: "" # Otherwise GitHub Pages will set this to "/craywatch"

# SOCIAL PROFILES
social:
  github: inbo/craywatch

# THEME SETTINGS (ALL OPTIONAL)
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.0
posts_on_home: false
tweets_on_home: false
archive_permalink: /blog/
github_edit: true
colors:
  links: "#ff6f61"
  banner: "#7d9b76"
  footer: "#7d9b76"
font_serif: false
logo: /assets/images/logo.png

# BUILD SETTINGS
repository: inbo/craywatch
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - ./R/

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: posts
    values:
      permalink: "/blog/:year/:slug/"
